/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class MSM {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

//  protected MSM(long cPtr, boolean cMemoryOwn) {
//    swigCMemOwn = cMemoryOwn;
//    swigCPtr = cPtr;
//  }
//
//  protected static long getCPtr(MSM obj) {
//    return (obj == null) ? 0 : obj.swigCPtr;
//  }
//
//  @SuppressWarnings("deprecation")
//  protected void finalize() {
//    delete();
//  }
//
//  public synchronized void delete() {
//    if (swigCPtr != 0) {
//      if (swigCMemOwn) {
//        swigCMemOwn = false;
//        MSMModuleJNI.delete_MSM(swigCPtr);
//      }
//      swigCPtr = 0;
//    }
//  }
//
//  public String getJson(String request) {
//    return MSMModuleJNI.MSM_getJson(swigCPtr, this, request);
//  }
//
//  public MSM() {
//    this(MSMModuleJNI.new_MSM(), true);
//  }

}
