/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MSMModuleJNI {
  public final static native void delete_MSM(long jarg1);
  public final static native String MSM_getJson(long jarg1, MSM jarg1_, String jarg2);
  public final static native long new_MSM();
}
